#!/bin/bash

export ANDROID_HOME="$HOME/.android/sdk"
export JAVA_HOME="$HOME/.android-studio/jre"
export PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin"

avd_name="$(avdmanager list avd | grep Name: | head -n 1 | awk '{ print $2 }')"
emulator @"$avd_name" &
